import type { TaxDefinition } from "./types"

export const TAX_DEFINITIONS: TaxDefinition[] = [
  {
    code: "ifta",
    name: "International Fuel Tax Agreement",
    shortName: "IFTA",
    jurisdiction: "Multi-jurisdictional",
    description: "Quarterly fuel-tax reporting for applicable interstate / cross-border operations.",
    frequencyOptions: ["quarterly"],
    defaultFrequency: "quarterly",
    accountLabel: "Account Number",
    accountRequired: true,
    companyField: "accIfta",
  },
  {
    code: "ct_huf",
    name: "Connecticut Highway Use Fee",
    shortName: "CT HUF",
    jurisdiction: "Connecticut",
    description: "Connecticut highway-use filing obligation for applicable carriers.",
    frequencyOptions: ["quarterly"],
    defaultFrequency: "quarterly",
    accountLabel: "Account Number",
    accountRequired: true,
    companyField: "accCt",
  },
  {
    code: "ny_hut",
    name: "New York Highway Use Tax",
    shortName: "NY HUT",
    jurisdiction: "New York",
    description: "Current filing frequency is company-specific and can move between quarterly and annual.",
    frequencyOptions: ["quarterly", "annual"],
    defaultFrequency: "quarterly",
    accountLabel: "Account Number",
    accountRequired: true,
    companyField: "accNyhut",
  },
  {
    code: "kyu",
    name: "Kentucky Weight Distance Tax / KYU",
    shortName: "KYU",
    jurisdiction: "Kentucky",
    description: "Kentucky weight-distance filing obligation for applicable carriers.",
    frequencyOptions: ["quarterly"],
    defaultFrequency: "quarterly",
    accountLabel: "Account Number",
    accountRequired: true,
    companyField: "accKyu",
  },
  {
    code: "nm_wdt",
    name: "New Mexico Weight Distance Tax",
    shortName: "NM WDT",
    jurisdiction: "New Mexico",
    description: "New Mexico weight-distance filing obligation for applicable carriers.",
    frequencyOptions: ["quarterly"],
    defaultFrequency: "quarterly",
    accountLabel: "Account Number",
    accountRequired: true,
    companyField: "accNm",
  },
  {
    code: "or_wmt",
    name: "Oregon Weight-Mile Tax",
    shortName: "OR WMT",
    jurisdiction: "Oregon",
    description: "Current company frequency may be monthly or quarterly.",
    frequencyOptions: ["monthly", "quarterly"],
    defaultFrequency: "monthly",
    accountLabel: "Account Number",
    accountRequired: true,
    companyField: "accOr",
  },
  {
    code: "form_2290",
    name: "Federal Heavy Highway Vehicle Use Tax — Form 2290",
    shortName: "Form 2290",
    jurisdiction: "United States — Federal",
    description: "Annual tax-period filing with event-based first-use obligations.",
    frequencyOptions: ["annual", "event-based"],
    defaultFrequency: "annual",
    accountLabel: "EIN / Filing Account Reference",
    accountRequired: false,
  },
  {
    code: "fuel_charge_registration",
    name: "Fuel Charge Registration",
    shortName: "Fuel Charge",
    jurisdiction: "Canada — Federal",
    description: "Retained for outstanding historical obligations and legacy records.",
    frequencyOptions: ["historical-only"],
    defaultFrequency: "historical-only",
    accountLabel: "Fuel Charge Registration Number",
    accountRequired: false,
    historicalOnly: true,
  },
  {
    code: "texas_excise_tax",
    name: "Texas Excise Tax",
    shortName: "Texas Excise",
    jurisdiction: "Texas",
    description: "Separate Texas excise / fuel-tax filing where applicable.",
    frequencyOptions: ["monthly", "quarterly"],
    defaultFrequency: "monthly",
    accountLabel: "Texas Tax Account Number",
    accountRequired: false,
  },
  {
    code: "arkansas_motor_fuel_tax",
    name: "Arkansas Motor Fuel Tax",
    shortName: "Arkansas MFT",
    jurisdiction: "Arkansas",
    description: "Most ordinary activity may be handled through IFTA; separate account schedules can vary.",
    frequencyOptions: ["quarterly", "monthly"],
    defaultFrequency: "quarterly",
    accountLabel: "Arkansas Tax Account Number",
    accountRequired: false,
  },
  {
    code: "ontario_tobacco_tax",
    name: "Ontario Tobacco Tax",
    shortName: "Ontario Tobacco",
    jurisdiction: "Ontario",
    description: "Ontario tobacco tax filing obligation for applicable interjurisdictional transport activity.",
    frequencyOptions: ["monthly"],
    defaultFrequency: "monthly",
    accountLabel: "Ontario Tobacco Tax Account / Permit Number",
    accountRequired: true,
  },
]
