import { normalizeName } from "@/lib/identifier-normalization"

export const DRIVER_MASTER_STORAGE_KEY = "tes_driver_masters_v1"
export const companyDriverStorageKey = (companyId: string) => `tes_company_drivers_${companyId}`

export type RecordType = "Employee" | "Owner-Operator" | "Contractor" | "Temporary Driver"
export type OperatingRegion = "Canada" | "United States" | "Cross-Border"
export type DriverStatus = "Active" | "On Leave" | "Suspended" | "Inactive" | "Terminated"
export type Country = "Canada" | "United States"
export type VerificationState = "Not Reviewed" | "Under Review" | "Source Matched" | "Difference Present" | "Externally Verified"
export type RecordState = "Draft" | "Current" | "Historical" | "Expired" | "Archived"

export type EffectiveRecord = { id:string; effectiveFrom:string; effectiveTo:string|null; status:"Current"|"Historical"; source:string; createdAt:string }
export type LicenceRecord = EffectiveRecord & {
  licenceNumberRaw:string; licenceNumberNormalized:string; jurisdiction:string; country:Country; documentType?:string; class?:string;
  endorsements?:string[]; restrictions?:string[]; airBrake?:string; issueDate?:string; expiryDate?:string; verificationState?:VerificationState;
  sourceEvidenceId?:string; sourceValue?:string; reviewedValue?:string; reviewReason?:string
}
export type AddressRecord = EffectiveRecord & { addressLine1:string; addressLine2?:string; city:string; stateProvince:string; postalZip:string; country:Country }
export type StatusHistory = EffectiveRecord & { statusValue:DriverStatus; reason?:string }
export type IdentityReference = { id:string; type:"DRIVER_LICENCE"|"OTHER"; value:string; jurisdiction?:string; country?:Country; createdAt:string; source:string }
export type JurisdictionReview = { id:string; status:"OPEN"|"RESOLVED"; reason:string; explanation:string; expectedResolutionDate?:string; createdAt:string; resolvedAt?:string }

export type DriverMaster = {
  id:string; createdAt:string; updatedAt:string;
  identity:{legalFirstName:string; legalMiddleName?:string; legalLastName:string; preferredName?:string; dateOfBirth:string}
  identityReferences:IdentityReference[]; licenceHistory:LicenceRecord[]; addressHistory:AddressRecord[];
  identityResolution:{status:"UNREVIEWED"|"CLEAR"|"REVIEW"; matchedDriverMasterId?:string; confidence?:"HIGH"|"MEDIUM"|"LOW"; notes?:string};
  jurisdictionReviews:JurisdictionReview[]; archive:{isArchived:boolean; archivedAt?:string; archiveReason?:string}
}

export type DriverApplication = {
  id:string; recordId:string; companyId:string; driverMasterId:string; relationshipId:string; status:"Draft"|"Invited"|"Started"|"Submitted"|"Under Review"|"Additional Information Requested"|"Approved"|"Rejected"|"Withdrawn"|"Expired"|"Invitation Cancelled";
  applicationDate?:string; submittedAt?:string; appliedRecordType?:RecordType; operatingRegion?:OperatingRegion;
  personal:{phone?:string;email?:string;addresses?:Array<{address:string;city:string;stateProvince:string;postalZip:string;country:Country;from?:string;to?:string}>};
  workAuthorization:{country?:Country;citizenshipOrAuthorization?:string;canTravelUS?:string;notes?:string};
  licenceDeclarations:Array<{country:Country;jurisdiction:string;number:string;class?:string;from?:string;to?:string;suspensionRevocation?:string}>;
  experience:Array<{equipmentOrOperation:string;years?:string;details?:string}>;
  collisions:Array<{date?:string;location?:string;description?:string;injuries?:string;fatalities?:string}>;
  citations:Array<{date?:string;jurisdiction?:string;description?:string;disposition?:string}>;
  employmentHistory:Array<{companyName:string;phone?:string;address?:string;city?:string;stateProvince?:string;contactName?:string;contactPosition?:string;position?:string;reasonForLeaving?:string;startDate?:string;endDate?:string;commercialMotorVehicle?:string;drugAlcoholProgram?:string}>;
  declarations:{englishCapability?:string;legalAge?:string;roadTestOrEquivalent?:string;oneValidLicence?:string;notDisqualified?:string;physicallyQualifiedDeclaration?:string};
  consents:Array<{type:string;version?:string;accepted:boolean;acceptedAt?:string}>;
  evidenceIds:string[]; createdAt:string; updatedAt:string
}

export type HiringPackageRecord = {
  id:string; recordId:string; companyId:string; driverMasterId:string; relationshipId:string; packageDate?:string; status:"Draft"|"Issued"|"Partially Completed"|"Completed"|"Under Review"|"Historical";
  employeeInformation:{phone?:string;email?:string;address?:string;city?:string;stateProvince?:string;postalZip?:string;country?:Country;emergencyContactName?:string;emergencyContactRelationship?:string;emergencyContactPhone?:string;emergencyContactEmail?:string;medicalConditionsOrAllergiesDeclared?:"Yes"|"No"|"Not Answered"};
  employmentAgreement:{agreementDate?:string;employerLegalName?:string;governingJurisdiction?:string;employeeAcknowledged?:boolean;signedDate?:string};
  orientationAcknowledgement:{orientationDate?:string;healthSafetyOrientation?:boolean;codeOfConduct?:boolean;harassmentViolencePrevention?:boolean;hazardAssessment?:boolean;alcoholDrugPolicy?:boolean;incidentReporting?:boolean;vehicleInspection?:boolean;fireEmergency?:boolean;ppe?:boolean;whmisHazardCommunication?:boolean;acknowledged?:boolean};
  companyVehicleAcknowledgement:{driverLicencePolicy?:boolean;medicalConditionReportingPolicy?:boolean;weatherConditions?:boolean;fuelCards?:boolean;vehicleInspection?:boolean;hosEld?:boolean;cargoSecurement?:boolean;defensiveDriving?:boolean;billOfLadingWaybills?:boolean;seatBelt?:boolean;distractedDriving?:boolean;speedLimits?:boolean;followingDistance?:boolean;weightsDimensions?:boolean;dangerousGoods?:boolean;trianglesWarningDevices?:boolean;daytimeRunningLights?:boolean;trainingAcknowledgement?:boolean;acknowledged?:boolean};
  substanceTestingConsent:{consentStatus:"Not Recorded"|"Consented"|"Declined";signedDate?:string};
  driverAbstractConsent:{consentStatus:"Not Recorded"|"Consented"|"Declined";signedDate?:string};
  evidenceIds:string[]; createdAt:string; updatedAt:string
}

export type TaxFormRecord = { id:string;recordId:string;formType:"TD1 Federal"|"TD1 Provincial/Territorial"|"Other";taxYear?:string;jurisdiction?:string;formVersion?:string;completedDate?:string;signedDate?:string;status:"Missing"|"Received"|"Under Review"|"Complete"|"Historical";evidenceIds:string[];createdAt:string;updatedAt:string }
export type CustomPolicyRecord = { id:string;recordId:string;policyName:string;policyVersion?:string;effectiveDate?:string;acknowledged?:boolean;acknowledgedDate?:string;status:"Current"|"Historical"|"Pending";evidenceIds:string[];createdAt:string;updatedAt:string }
export type EvidenceRecord = { id:string;recordId:string;category:string;fileName:string;mimeType?:string;dataUrl?:string;source:"Upload"|"Camera"|"Generated"|"External";verificationState:VerificationState;createdAt:string;linkedRecordId?:string;notes?:string }

export type QualificationRecord = { id:string;recordId:string;type:string;title:string;applicable:"Yes"|"No"|"Unknown";status:"Current"|"Requirement Not Current"|"Under Review"|"Historical"|"Not Applicable";effectiveDate?:string;expiryDate?:string;sourceType?:string;sourceRecordId?:string;notes?:string;createdAt:string;updatedAt:string }
export type ExperienceRecord = { id:string;recordId:string;category:string;declaredYears?:number;supportedYears?:number;sourceRecordIds:string[];notes?:string;createdAt:string;updatedAt:string }
export type ScreeningRecord = { id:string;recordId:string;type:"Employment History Verification"|"Clearinghouse Query"|"PSP"|"Road Test"|"Criminal / Background Screening"|"Periodic Driver Review"|"Custom Screening";recordDate:string;status:string;result?:string;dueDate?:string;expiryDate?:string;provider?:string;sourceRecordId?:string;notes?:string;evidenceIds:string[];createdAt:string;updatedAt:string }
export type MedicalRecord = { id:string;recordId:string;recordDate:string;regime?:string;examiner?:string;examinerRegistryNumber?:string;qualificationStatus:"Qualified"|"Qualified with Limitation"|"Temporarily Not Qualified"|"Not Qualified"|"Pending";effectiveDate?:string;expirationDate?:string;limitations?:string;verificationState:VerificationState;evidenceIds:string[];createdAt:string;updatedAt:string }
export type DrugAlcoholRecord = { id:string;recordId:string;testType:"Pre-Employment"|"Random"|"Post-Accident"|"Reasonable Suspicion / Cause"|"Return-to-Duty"|"Follow-Up";testDate:string;complianceStatus:string;resultStatus?:string;followUpRequired?:boolean;relatedEventId?:string;evidenceIds:string[];createdAt:string;updatedAt:string }
export type TrainingRecord = { id:string;recordId:string;course:string;trainingType:"Initial"|"Refresher"|"External / Historical"|"Remedial"|"Other";recordStatus:"Assigned"|"Scheduled"|"In Progress"|"Completed"|"Cancelled"|"Exempted";assessmentResult?:"Passed"|"Failed"|"Incomplete"|"Pending"|"Not Required";assignedDate?:string;dueDate?:string;completionDate?:string;provider?:string;instructor?:string;deliveryMethod?:string;duration?:string;certificateNumber?:string;issueDate?:string;expirationDate?:string;nextDueDate?:string;evidenceIds:string[];previousTrainingRecordId?:string;createdAt:string;updatedAt:string }
export type HosSummary = { id:string;recordId:string;date:string;drivingMinutes?:number;onDutyMinutes?:number;offDutyMinutes?:number;sleeperMinutes?:number;potentialViolationCount?:number;confirmedViolationCount?:number;unassignedDrivingMinutes?:number;uncertifiedLogCount?:number;ruleProfile?:string;source?:string;createdAt:string;updatedAt:string }
export type HosViolation = { id:string;recordId:string;violationType:string;detectedAt:string;startAt?:string;endAt?:string;durationMinutes?:number;ruleProfile?:string;vehicleId?:string;tripId?:string;location?:string;detectionStatus:"Potential"|"Under Review"|"Confirmed"|"Not a Violation"|"Unable to Determine"|"Disputed"|"Resolved";companyDetermination?:string;companyDeterminationBy?:string;companyDeterminationAt?:string;relatedTrainingRecordId?:string;relatedEventId?:string;notes?:string;createdAt:string;updatedAt:string }
export type EventLink = { id:string;recordId:string;eventId:string;eventCategory:string;eventDate:string;title:string;status?:string;vehicleId?:string;tripId?:string;location?:string;summary?:string;companyDetermination?:string;createdAt:string }

export type CompanyDriverRelationship = {
  id:string; recordId?:string; companyId:string; driverMasterId:string; recordType:RecordType; operatingRegion:OperatingRegion; driverStatus:DriverStatus; startDate:string; endDate?:string;
  statusHistory:StatusHistory[]; createdAt:string; updatedAt:string; archive:{isArchived:boolean; archivedAt?:string; archiveReason?:string}
}
export type DriverMasterStore = {version:1;drivers:DriverMaster[]}
export type CompanyDriverStore = {version:1;companyId:string;relationships:CompanyDriverRelationship[];applications?:DriverApplication[];hiringPackages?:HiringPackageRecord[];taxForms?:TaxFormRecord[];customPolicies?:CustomPolicyRecord[];evidence?:EvidenceRecord[];qualifications?:QualificationRecord[];experience?:ExperienceRecord[];screenings?:ScreeningRecord[];medicalRecords?:MedicalRecord[];drugAlcoholRecords?:DrugAlcoholRecord[];trainingRecords?:TrainingRecord[];hosSummaries?:HosSummary[];hosViolations?:HosViolation[];eventLinks?:EventLink[]}

const read=<T,>(key:string,fallback:T):T=>{if(typeof window==="undefined")return fallback;try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}}
const write=<T,>(key:string,value:T)=>{if(typeof window==="undefined")throw new Error("Driver persistence requires a browser context.");localStorage.setItem(key,JSON.stringify(value))}
const uid=(prefix:string)=>`${prefix}-${typeof crypto!=="undefined"&&crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`}`
const clean=(v?:string)=>String(v||"").trim()
export const normalizeLicenceNumber=(v:string)=>clean(v).toUpperCase().replace(/[^A-Z0-9]/g,"")
const person=(v:string)=>normalizeName(v).toLowerCase()

export const loadDriverMasterStore=():DriverMasterStore=>{const raw=read<any>(DRIVER_MASTER_STORAGE_KEY,null);if(raw&&typeof raw==="object"&&Array.isArray(raw.drivers))return {version:1,drivers:raw.drivers};return {version:1,drivers:[]}}
export const saveDriverMasterStore=(s:DriverMasterStore)=>write(DRIVER_MASTER_STORAGE_KEY,s)
export const loadCompanyDriverStore=(companyId:string):CompanyDriverStore=>{const raw=read<any>(companyDriverStorageKey(companyId),null);const base:CompanyDriverStore={version:1,companyId,relationships:[],applications:[],hiringPackages:[],taxForms:[],customPolicies:[],evidence:[],qualifications:[],experience:[],screenings:[],medicalRecords:[],drugAlcoholRecords:[],trainingRecords:[],hosSummaries:[],hosViolations:[],eventLinks:[]};if(Array.isArray(raw))return {...base,relationships:raw};if(raw&&typeof raw==="object")return {...base,...raw,version:1,companyId,relationships:Array.isArray(raw.relationships)?raw.relationships:[]};return base}
export const saveCompanyDriverStore=(s:CompanyDriverStore)=>write(companyDriverStorageKey(s.companyId),s)
export const readCompanies=()=>read<any[]>("tes_companies",[]).filter(x=>x&&x.id).map(x=>({id:String(x.id),name:String(x.name||x.companyName||""),status:x.status,region:x.region}))
export const getCompany=(id:string)=>readCompanies().find(c=>c.id===id)||null
export const fullLegalName=(d:DriverMaster)=>[d.identity.legalFirstName,d.identity.legalMiddleName,d.identity.legalLastName].filter(Boolean).join(" ")
export const currentLicence=(d:DriverMaster)=>[...d.licenceHistory].filter(x=>!x.effectiveTo).sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom))[0]
export const currentAddress=(d:DriverMaster)=>[...d.addressHistory].filter(x=>!x.effectiveTo).sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom))[0]
export const calculateAge=(dob:string,today=new Date())=>{const d=new Date(`${dob}T00:00:00`);if(Number.isNaN(d.getTime()))return null;let a=today.getFullYear()-d.getFullYear();const m=today.getMonth()-d.getMonth();if(m<0||(m===0&&today.getDate()<d.getDate()))a--;return a>=0?a:null}

function companyToken(companyId:string){const t=companyId.toUpperCase().replace(/[^A-Z0-9]/g,"");return (t.slice(-6)||"COMP").padStart(4,"0")}
function randomMasterId(){const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";const part=()=>Array.from({length:4},()=>alphabet[Math.floor(Math.random()*alphabet.length)]).join("");return `DRV-${part()}-${part()}-${part()}`}
export function allocateDriverMasterId(drivers:DriverMaster[]){for(let i=0;i<100;i++){const candidate=randomMasterId();if(!drivers.some(d=>d.id===candidate))return candidate}throw new Error("Unable to allocate unique Driver Master ID.")}
export function allocateCompanyRecordId(companyId:string,relationships:CompanyDriverRelationship[]){const token=companyToken(companyId);const used=new Set(relationships.map(r=>r.recordId?.match(/-DRV-(\d+)$/)?.[1]).filter(Boolean).map(Number));let n=1;while(used.has(n))n++;return `${token}-DRV-${String(n).padStart(6,"0")}`}
export function displayCompanyDriverRecordId(companyId:string,r:CompanyDriverRelationship){return r.recordId||`${companyToken(companyId)}-DRV-LEGACY`}
export function allocateSubRecordId(companyId:string,code:string,existing:Array<{recordId?:string}>){const token=companyToken(companyId),rx=new RegExp(`-${code}-(\\d+)$`);const used=new Set(existing.map(r=>r.recordId?.match(rx)?.[1]).filter(Boolean).map(Number));let n=1;while(used.has(n))n++;return `${token}-${code}-${String(n).padStart(6,"0")}`}

export type DriverInput={legalFirstName:string;legalMiddleName:string;legalLastName:string;preferredName:string;dateOfBirth:string;recordType:RecordType;operatingRegion:OperatingRegion;driverStatus:DriverStatus;relationshipStartDate:string;relationshipEndDate:string;addressLine1:string;addressLine2:string;city:string;stateProvince:string;postalZip:string;country:Country;addressEffectiveFrom:string;licenceNumber:string;licenceJurisdiction:string;licenceCountry:Country;licenceClass:string;licenceEffectiveFrom:string;jurisdictionReview?:{reason:string;explanation:string;expectedResolutionDate:string}}
export function validatePostalZip(country:Country,value:string){const v=clean(value).toUpperCase();return country==="Canada"?/^[A-Z]\d[A-Z][ -]?\d[A-Z]\d$/.test(v):/^\d{5}(-\d{4})?$/.test(v)}
export function validateDriverInput(x:DriverInput){const required:[string,string][]=[["Legal First Name",x.legalFirstName],["Legal Last Name",x.legalLastName],["Date of Birth",x.dateOfBirth],["Record Type",x.recordType],["Operating Region",x.operatingRegion],["Driver Status",x.driverStatus],["Relationship Start Date",x.relationshipStartDate],["Address",x.addressLine1],["City",x.city],["State / Province",x.stateProvince],["Postal / ZIP",x.postalZip],["Address Effective From",x.addressEffectiveFrom],["Licence Number",x.licenceNumber],["Licence Jurisdiction",x.licenceJurisdiction],["Licence Effective From",x.licenceEffectiveFrom]];const miss=required.filter(([,v])=>!clean(v)).map(([k])=>k);if(miss.length)throw new Error(`Required: ${miss.join(", ")}.`);if(!validatePostalZip(x.country,x.postalZip))throw new Error(x.country==="Canada"?"Enter a valid Canadian postal code.":"Enter a valid U.S. ZIP or ZIP+4.");if(!normalizeLicenceNumber(x.licenceNumber))throw new Error("Licence number is required.")}

export type IdentityMatch={kind:"EXACT_LICENCE"|"STRONG"|"POSSIBLE"|"NONE";master?:DriverMaster;reasons:string[]}
export function findDriverIdentityMatch(x:Pick<DriverInput,"legalFirstName"|"legalLastName"|"dateOfBirth"|"licenceNumber"|"licenceJurisdiction"|"licenceCountry">,drivers=loadDriverMasterStore().drivers):IdentityMatch{
 const lic=normalizeLicenceNumber(x.licenceNumber),fn=person(x.legalFirstName),ln=person(x.legalLastName);let possible:DriverMaster|undefined;let reasons:string[]=[]
 for(const d of drivers){const exactLicence=d.licenceHistory.some(l=>normalizeLicenceNumber(l.licenceNumberNormalized||l.licenceNumberRaw||"")===lic&&l.jurisdiction===x.licenceJurisdiction&&l.country===x.licenceCountry);if(lic&&exactLicence)return{kind:"EXACT_LICENCE",master:d,reasons:["Same licence number and issuing jurisdiction"]};const sameName=person(d.identity.legalFirstName)===fn&&person(d.identity.legalLastName)===ln;const sameDob=d.identity.dateOfBirth===x.dateOfBirth;if(sameName&&sameDob)return{kind:"STRONG",master:d,reasons:["Same legal name and date of birth"]};if(sameName||sameDob){possible=d;reasons=[sameName?"Same legal name":"Same date of birth"]}}
 return possible?{kind:"POSSIBLE",master:possible,reasons}:{kind:"NONE",reasons:[]}
}

export function createDriver(companyId:string,x:DriverInput,options?:{reuseDriverMasterId?:string}){validateDriverInput(x);const beforeM=loadDriverMasterStore(),beforeC=loadCompanyDriverStore(companyId);const match=findDriverIdentityMatch(x,beforeM.drivers);if(match.kind==="POSSIBLE"&&!options?.reuseDriverMasterId)throw new Error(`Possible existing Driver match: ${match.master?.id}. Review identity before creating a new Driver Master.`);if((match.kind==="EXACT_LICENCE"||match.kind==="STRONG")&&!options?.reuseDriverMasterId)throw new Error(`Existing Driver Master found: ${match.master?.id}. Confirm reuse instead of creating a duplicate.`);const now=new Date().toISOString();let master=options?.reuseDriverMasterId?beforeM.drivers.find(d=>d.id===options.reuseDriverMasterId):undefined;if(options?.reuseDriverMasterId&&!master)throw new Error("Selected Driver Master was not found.");if(!master){const id=allocateDriverMasterId(beforeM.drivers);master={id,createdAt:now,updatedAt:now,identity:{legalFirstName:normalizeName(x.legalFirstName),legalMiddleName:normalizeName(x.legalMiddleName)||undefined,legalLastName:normalizeName(x.legalLastName),preferredName:normalizeName(x.preferredName)||undefined,dateOfBirth:x.dateOfBirth},identityReferences:[{id:uid("IDR"),type:"DRIVER_LICENCE",value:normalizeLicenceNumber(x.licenceNumber),jurisdiction:x.licenceJurisdiction,country:x.licenceCountry,createdAt:now,source:"Driver onboarding"}],licenceHistory:[{id:uid("LIC"),licenceNumberRaw:x.licenceNumber.trim(),licenceNumberNormalized:normalizeLicenceNumber(x.licenceNumber),jurisdiction:x.licenceJurisdiction,country:x.licenceCountry,class:clean(x.licenceClass)||undefined,effectiveFrom:x.licenceEffectiveFrom,effectiveTo:null,status:"Current",source:"Driver onboarding",createdAt:now,verificationState:"Not Reviewed"}],addressHistory:[{id:uid("ADR"),addressLine1:clean(x.addressLine1),addressLine2:clean(x.addressLine2)||undefined,city:clean(x.city),stateProvince:x.stateProvince,postalZip:x.postalZip.trim().toUpperCase(),country:x.country,effectiveFrom:x.addressEffectiveFrom,effectiveTo:null,status:"Current",source:"Driver onboarding",createdAt:now}],identityResolution:{status:x.stateProvince===x.licenceJurisdiction?"CLEAR":"REVIEW"},jurisdictionReviews:x.stateProvince!==x.licenceJurisdiction?[{id:uid("JUR"),status:"OPEN",reason:x.jurisdictionReview?.reason||"Residence and licence jurisdictions differ",explanation:x.jurisdictionReview?.explanation||"",expectedResolutionDate:x.jurisdictionReview?.expectedResolutionDate||undefined,createdAt:now}]:[],archive:{isArchived:false}}}
 if(beforeC.relationships.some(r=>r.driverMasterId===master!.id&&!r.archive.isArchived))throw new Error("This Driver already has an active company relationship.");const relationship:CompanyDriverRelationship={id:uid("CDR"),recordId:allocateCompanyRecordId(companyId,beforeC.relationships),companyId,driverMasterId:master.id,recordType:x.recordType,operatingRegion:x.operatingRegion,driverStatus:x.driverStatus,startDate:x.relationshipStartDate,endDate:x.relationshipEndDate||undefined,statusHistory:[{id:uid("STA"),statusValue:x.driverStatus,effectiveFrom:x.relationshipStartDate,effectiveTo:null,status:"Current",source:"Driver onboarding",createdAt:now,reason:"Initial company Driver relationship"}],createdAt:now,updatedAt:now,archive:{isArchived:false}};const nextM=beforeM.drivers.some(d=>d.id===master!.id)?beforeM:{version:1,drivers:[...beforeM.drivers,master]};const nextC={...beforeC,relationships:[...beforeC.relationships,relationship]};try{saveDriverMasterStore(nextM);try{saveCompanyDriverStore(nextC)}catch(e){saveDriverMasterStore(beforeM);throw e}}catch(e){try{saveCompanyDriverStore(beforeC)}catch{};throw e}return{master,relationship}}

export function updateDriverProfileAtomic(companyId:string,driverId:string,input:{identity:DriverMaster["identity"];recordType:RecordType;operatingRegion:OperatingRegion;driverStatus:DriverStatus;relationshipStartDate:string;relationshipEndDate?:string;address?:Omit<AddressRecord,"id"|"status"|"source"|"createdAt"|"effectiveTo">}){const bm=loadDriverMasterStore(),bc=loadCompanyDriverStore(companyId),d=bm.drivers.find(v=>v.id===driverId),r=bc.relationships.find(v=>v.driverMasterId===driverId&&!v.archive.isArchived);if(!d||!r)throw new Error("Driver record not found.");if(!clean(input.identity.legalFirstName)||!clean(input.identity.legalLastName)||!input.identity.dateOfBirth)throw new Error("Legal first name, legal last name and date of birth are required.");const now=new Date().toISOString();let addresses=d.addressHistory;if(input.address){if(!validatePostalZip(input.address.country,input.address.postalZip))throw new Error("Postal / ZIP format is invalid.");const current=currentAddress(d);if(!current||[current.addressLine1,current.addressLine2,current.city,current.stateProvince,current.postalZip,current.country].join("|")!==[input.address.addressLine1,input.address.addressLine2,input.address.city,input.address.stateProvince,input.address.postalZip,input.address.country].join("|")){if(current&&input.address.effectiveFrom<=current.effectiveFrom)throw new Error("New address effective date must be after the current address effective date.");addresses=d.addressHistory.map(a=>!a.effectiveTo?{...a,effectiveTo:input.address!.effectiveFrom,status:"Historical" as const}:a);addresses.push({id:uid("ADR"),...input.address,effectiveTo:null,status:"Current",source:"Driver Profile",createdAt:now})}}
 const updatedD={...d,identity:{legalFirstName:normalizeName(input.identity.legalFirstName),legalMiddleName:normalizeName(input.identity.legalMiddleName||"")||undefined,legalLastName:normalizeName(input.identity.legalLastName),preferredName:normalizeName(input.identity.preferredName||"")||undefined,dateOfBirth:input.identity.dateOfBirth},addressHistory:addresses,updatedAt:now};let statusHistory=r.statusHistory;if(input.driverStatus!==r.driverStatus){const last=[...statusHistory].filter(s=>!s.effectiveTo).sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom))[0];if(last&&input.relationshipStartDate<=last.effectiveFrom)throw new Error("Status effective date must be after the current status effective date.");statusHistory=statusHistory.map(s=>!s.effectiveTo?{...s,effectiveTo:input.relationshipStartDate,status:"Historical" as const}:s);statusHistory.push({id:uid("STA"),statusValue:input.driverStatus,effectiveFrom:input.relationshipStartDate,effectiveTo:null,status:"Current",source:"Driver Profile",createdAt:now,reason:"Company Driver status changed"})}const updatedR={...r,recordType:input.recordType,operatingRegion:input.operatingRegion,driverStatus:input.driverStatus,startDate:input.relationshipStartDate,endDate:input.relationshipEndDate,statusHistory,updatedAt:now};try{saveDriverMasterStore({...bm,drivers:bm.drivers.map(v=>v.id===driverId?updatedD:v)});try{saveCompanyDriverStore({...bc,relationships:bc.relationships.map(v=>v.id===r.id?updatedR:v)})}catch(e){saveDriverMasterStore(bm);throw e}}catch(e){try{saveCompanyDriverStore(bc)}catch{};throw e}return{master:updatedD,relationship:updatedR}}

export function addLicence(companyId:string,driverId:string,input:{licenceNumberRaw:string;jurisdiction:string;country:Country;documentType?:string;class?:string;endorsements?:string[];restrictions?:string[];airBrake?:string;issueDate?:string;expiryDate?:string;effectiveFrom:string;verificationState?:VerificationState;sourceEvidenceId?:string;sourceValue?:string;reviewedValue?:string;reviewReason?:string}){const s=loadDriverMasterStore(),d=s.drivers.find(x=>x.id===driverId);if(!d)throw new Error("Driver not found.");if(!input.effectiveFrom||!input.licenceNumberRaw||!input.jurisdiction)throw new Error("Licence number, jurisdiction and effective date are required.");if(input.issueDate&&input.expiryDate&&input.issueDate>input.expiryDate)throw new Error("Licence issue date cannot be after expiry date.");const current=currentLicence(d);if(current&&input.effectiveFrom<=current.effectiveFrom)throw new Error("New licence effective date must be after the current licence effective date.");const normalized=normalizeLicenceNumber(input.licenceNumberRaw);for(const other of s.drivers){if(other.id===driverId)continue;if(other.licenceHistory.some(l=>normalizeLicenceNumber(l.licenceNumberNormalized||l.licenceNumberRaw)===normalized&&l.country===input.country&&l.jurisdiction===input.jurisdiction))throw new Error(`Licence identifier is already linked to Driver Master ${other.id}.`)}const now=new Date().toISOString();const history=d.licenceHistory.map(l=>!l.effectiveTo?{...l,effectiveTo:input.effectiveFrom,status:"Historical" as const}:l);history.push({id:uid("LIC"),...input,licenceNumberNormalized:normalized,effectiveTo:null,status:"Current",source:"Qualifications & Licensing",createdAt:now});const updated={...d,licenceHistory:history,identityReferences:[...d.identityReferences,{id:uid("IDR"),type:"DRIVER_LICENCE" as const,value:normalized,jurisdiction:input.jurisdiction,country:input.country,createdAt:now,source:"Qualifications & Licensing"}],updatedAt:now};saveDriverMasterStore({...s,drivers:s.drivers.map(x=>x.id===driverId?updated:x)});return updated}

export function updateCompanyDriverStore(companyId:string,mutator:(store:CompanyDriverStore)=>CompanyDriverStore){const before=loadCompanyDriverStore(companyId);const next=mutator(structuredClone(before));saveCompanyDriverStore(next);return next}
export const makeInternalId=uid
export function createRecord<T extends object>(companyId:string,code:string,collection:Array<{recordId?:string}>,data:T){const now=new Date().toISOString();return {id:uid(code),recordId:allocateSubRecordId(companyId,code,collection),...data,createdAt:now,updatedAt:now}}
