import type { TrainingCourseDefinition } from "@/types/drivers"

/**
 * Canonical TES Driver training taxonomy.
 *
 * IMPORTANT:
 * - Catalog membership does not assert legal applicability, company requirement,
 *   assignment, or completion status.
 * - courseId/courseCode are stable identities; display titles are not identities.
 * - Historical/unknown titles are intentionally not fuzzy-mapped here.
 */
export const DRIVER_TRAINING_CATEGORY = {
  VEHICLE_OPERATION_SAFETY: "DRV-TRN-CAT-VEHICLE-OPERATION-SAFETY",
  REGULATORY_COMPLIANCE: "DRV-TRN-CAT-REGULATORY-COMPLIANCE",
  EMERGENCY_HEALTH_SECURITY: "DRV-TRN-CAT-EMERGENCY-HEALTH-SECURITY",
  WORKPLACE_PROFESSIONAL: "DRV-TRN-CAT-WORKPLACE-PROFESSIONAL",
} as const

export const DRIVER_TRAINING_CATEGORIES = [
  {
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    code: "VEHICLE_OPERATION_SAFETY",
    title: "Vehicle Operation and Safety",
  },
  {
    categoryId: DRIVER_TRAINING_CATEGORY.REGULATORY_COMPLIANCE,
    code: "REGULATORY_COMPLIANCE",
    title: "Regulatory / Compliance",
  },
  {
    categoryId: DRIVER_TRAINING_CATEGORY.EMERGENCY_HEALTH_SECURITY,
    code: "EMERGENCY_HEALTH_SECURITY",
    title: "Emergency / Health / Security",
  },
  {
    categoryId: DRIVER_TRAINING_CATEGORY.WORKPLACE_PROFESSIONAL,
    code: "WORKPLACE_PROFESSIONAL",
    title: "Workplace / Professional",
  },
] as const

export const TRAINING_COURSE_CATALOG: TrainingCourseDefinition[] = [
  // Vehicle Operation and Safety
  {
    courseId: "DRV-TRN-DVIR",
    courseCode: "DRV-TRN-DVIR",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Commercial Vehicle Inspection / DVIR",
    description: "Commercial vehicle inspection and driver vehicle inspection reporting training.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-DEFENSIVE",
    courseCode: "DRV-TRN-DEFENSIVE",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Defensive Driving",
    description: "Defensive driving principles for commercial vehicle operations.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-HOS-ELD",
    courseCode: "DRV-TRN-HOS-ELD",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Hours of Service / ELD / Logbook Compliance",
    description: "Hours-of-service, electronic logging device, and logbook compliance training.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-CARGO",
    courseCode: "DRV-TRN-CARGO",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Cargo Securement",
    description: "Cargo securement practices for applicable commercial vehicle operations.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-ACCIDENT-REPORTING",
    courseCode: "DRV-TRN-ACCIDENT-REPORTING",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Accident Scene Reporting / Post-Accident Procedures",
    description: "Accident-scene reporting, evidence preservation, notification, and post-accident procedures.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-DISTRACTED",
    courseCode: "DRV-TRN-DISTRACTED",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Distracted Driving Prevention",
    description: "Prevention of mobile-device, in-cab, and other driver distractions.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-BACKING",
    courseCode: "DRV-TRN-BACKING",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Backing / Parking / Low-Speed Maneuvering",
    description: "Safe backing, parking, spotter use, and low-speed commercial vehicle maneuvering.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-SPACE-MANAGEMENT",
    courseCode: "DRV-TRN-SPACE-MANAGEMENT",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Space Management / Following Distance / Speed Management",
    description: "Managing following distance, vehicle space, speed, and stopping margins.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-FATIGUE",
    courseCode: "DRV-TRN-FATIGUE",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Fatigue Management / Fitness for Duty",
    description: "Fatigue risk management and fitness-for-duty practices for drivers.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-COUPLING",
    courseCode: "DRV-TRN-COUPLING",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Coupling / Uncoupling / Trailer Connection",
    description: "Safe coupling, uncoupling, fifth-wheel, trailer connection, and verification procedures.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-LOADING",
    courseCode: "DRV-TRN-LOADING",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Loading / Unloading / Dock Safety",
    description: "Safe loading, unloading, dock operations, and vehicle-positioning practices.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-WEIGHTS-DIMENSIONS",
    courseCode: "DRV-TRN-WEIGHTS-DIMENSIONS",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Weights / Dimensions / Axle Limits / Scale Procedures",
    description: "Vehicle weights, dimensions, axle limits, weighing, and scale procedures.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-ROUTE-PLANNING",
    courseCode: "DRV-TRN-ROUTE-PLANNING",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Route Planning / Bridge Clearance / Low-Clearance Awareness",
    description: "Commercial route planning with bridge, height, weight, and low-clearance awareness.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-WINTER",
    courseCode: "DRV-TRN-WINTER",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Winter Driving & Adverse Weather Operations",
    description: "Winter driving and adverse-weather operational training.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-BRAKE",
    courseCode: "DRV-TRN-BRAKE",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Mountain / Grade / Brake Management",
    description: "Mountain, grade, speed, braking, and descent-management operations training.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-AIRBRAKE",
    courseCode: "DRV-TRN-AIRBRAKE",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Commercial Vehicle Air Brake Systems & Pre-Trip Air Loss Tests",
    description: "Existing TES air-brake training concept retained as a distinct course.",
    version: "1",
    state: "ACTIVE",
    defaultValidityPeriodMonths: 36,
  },
  {
    courseId: "DRV-TRN-TIRE-BRAKE-BREAKDOWN",
    courseCode: "DRV-TRN-TIRE-BRAKE-BREAKDOWN",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Tire / Brake / Roadside Breakdown Procedures",
    description: "Tire, brake, roadside breakdown, hazard-control, and safe roadside procedure training.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-ROADSIDE-INSPECTIONS",
    courseCode: "DRV-TRN-ROADSIDE-INSPECTIONS",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Roadside Inspections / Enforcement Interaction",
    description: "Roadside inspection preparation and safe, professional interaction with enforcement personnel.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-ROAD-USER-WORKZONE",
    courseCode: "DRV-TRN-ROAD-USER-WORKZONE",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Wildlife / Pedestrian / Cyclist / Work-Zone Safety",
    description: "Commercial driving safety around wildlife, vulnerable road users, and work zones.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-RAILROAD",
    courseCode: "DRV-TRN-RAILROAD",
    categoryId: DRIVER_TRAINING_CATEGORY.VEHICLE_OPERATION_SAFETY,
    title: "Railroad Crossing Safety",
    description: "Safe commercial vehicle approach, stopping, and crossing procedures at railroad crossings.",
    version: "1",
    state: "ACTIVE",
  },

  // Regulatory / Compliance
  {
    courseId: "DRV-TRN-NSC-FMCSA",
    courseCode: "DRV-TRN-NSC-FMCSA",
    categoryId: DRIVER_TRAINING_CATEGORY.REGULATORY_COMPLIANCE,
    title: "NSC / FMCSA Fundamentals",
    description: "National Safety Code and FMCSA regulatory fundamentals relevant to commercial drivers.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-ELDT",
    courseCode: "DRV-TRN-ELDT",
    categoryId: DRIVER_TRAINING_CATEGORY.REGULATORY_COMPLIANCE,
    title: "Mandatory Entry-Level / ELDT",
    description: "Entry-level driver training requirements and applicable ELDT curriculum.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-DRUG-ALCOHOL",
    courseCode: "DRV-TRN-DRUG-ALCOHOL",
    categoryId: DRIVER_TRAINING_CATEGORY.REGULATORY_COMPLIANCE,
    title: "Drug & Alcohol Policy / Reasonable Suspicion / Testing",
    description: "Commercial driver drug-and-alcohol policy, reasonable-suspicion indicators, and testing procedures.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-TDG-HAZMAT",
    courseCode: "DRV-TRN-TDG-HAZMAT",
    categoryId: DRIVER_TRAINING_CATEGORY.REGULATORY_COMPLIANCE,
    title: "Transportation of Dangerous Goods (TDG) / Hazmat Compliance",
    description: "Applicable dangerous-goods / hazmat transportation compliance training.",
    version: "1",
    state: "ACTIVE",
    defaultValidityPeriodMonths: 36,
  },
  {
    courseId: "DRV-TRN-TDG-EMERGENCY",
    courseCode: "DRV-TRN-TDG-EMERGENCY",
    categoryId: DRIVER_TRAINING_CATEGORY.REGULATORY_COMPLIANCE,
    title: "Dangerous Goods / Hazmat Emergency Response",
    description: "Emergency response procedures for incidents involving dangerous goods or hazardous materials.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-WHMIS",
    courseCode: "DRV-TRN-WHMIS",
    categoryId: DRIVER_TRAINING_CATEGORY.REGULATORY_COMPLIANCE,
    title: "WHMIS / Hazard Communication",
    description: "Workplace hazardous-material identification, labeling, SDS, and hazard communication.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-CROSS-BORDER",
    courseCode: "DRV-TRN-CROSS-BORDER",
    categoryId: DRIVER_TRAINING_CATEGORY.REGULATORY_COMPLIANCE,
    title: "Cross-Border Canada-US Documentation / Customs",
    description: "Canada-US cross-border documentation, customs, and driver compliance procedures.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-ELD-TELEMATICS",
    courseCode: "DRV-TRN-ELD-TELEMATICS",
    categoryId: DRIVER_TRAINING_CATEGORY.REGULATORY_COMPLIANCE,
    title: "ELD / Telematics / In-Cab Systems",
    description: "Operational use of ELD, telematics, and required in-cab systems.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-ELECTRONIC-INSPECTION",
    courseCode: "DRV-TRN-ELECTRONIC-INSPECTION",
    categoryId: DRIVER_TRAINING_CATEGORY.REGULATORY_COMPLIANCE,
    title: "Electronic Inspection Reports / Defect Reporting / Maintenance Communication",
    description: "Electronic inspection reporting, defect reporting, and communication with maintenance.",
    version: "1",
    state: "ACTIVE",
  },

  // Emergency / Health / Security
  {
    courseId: "DRV-TRN-SECURITY",
    courseCode: "DRV-TRN-SECURITY",
    categoryId: DRIVER_TRAINING_CATEGORY.EMERGENCY_HEALTH_SECURITY,
    title: "Security Awareness / Cargo Theft / Facility Security",
    description: "Security awareness, cargo-theft prevention, and facility-security practices.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-FIRE",
    courseCode: "DRV-TRN-FIRE",
    categoryId: DRIVER_TRAINING_CATEGORY.EMERGENCY_HEALTH_SECURITY,
    title: "Fire Safety / Fire Extinguisher",
    description: "Fire prevention, response, extinguisher awareness, and safe evacuation practices.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-FIRST-AID",
    courseCode: "DRV-TRN-FIRST-AID",
    categoryId: DRIVER_TRAINING_CATEGORY.EMERGENCY_HEALTH_SECURITY,
    title: "First Aid / CPR / Emergency Response",
    description: "First aid, CPR, and immediate emergency-response fundamentals.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-EVACUATION",
    courseCode: "DRV-TRN-EVACUATION",
    categoryId: DRIVER_TRAINING_CATEGORY.EMERGENCY_HEALTH_SECURITY,
    title: "Emergency Evacuation / Severe Weather / Security Incident",
    description: "Emergency evacuation, severe-weather response, and security-incident procedures.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-HAZARD-PREVENTION",
    courseCode: "DRV-TRN-HAZARD-PREVENTION",
    categoryId: DRIVER_TRAINING_CATEGORY.EMERGENCY_HEALTH_SECURITY,
    title: "Federal Hazard Prevention / Occupational Health & Safety",
    description: "Federal hazard-prevention principles and occupational health and safety practices.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-PPE",
    courseCode: "DRV-TRN-PPE",
    categoryId: DRIVER_TRAINING_CATEGORY.EMERGENCY_HEALTH_SECURITY,
    title: "PPE / Slip-Trip-Fall Prevention",
    description: "Personal protective equipment and slip, trip, and fall prevention.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-LONE-WORKER",
    courseCode: "DRV-TRN-LONE-WORKER",
    categoryId: DRIVER_TRAINING_CATEGORY.EMERGENCY_HEALTH_SECURITY,
    title: "Lone Worker Safety",
    description: "Risk controls and emergency practices for lone-worker operations.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-FOOD-SAFETY",
    courseCode: "DRV-TRN-FOOD-SAFETY",
    categoryId: DRIVER_TRAINING_CATEGORY.EMERGENCY_HEALTH_SECURITY,
    title: "Food Safety / Temperature-Controlled Operations",
    description: "Food safety and temperature-control practices for applicable operations.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-TANKER",
    courseCode: "DRV-TRN-TANKER",
    categoryId: DRIVER_TRAINING_CATEGORY.EMERGENCY_HEALTH_SECURITY,
    title: "Tanker / Liquid Surge",
    description: "Tanker operations, liquid surge awareness, and safe handling of liquid cargo.",
    version: "1",
    state: "ACTIVE",
  },

  // Workplace / Professional
  {
    courseId: "DRV-TRN-HARASSMENT-VIOLENCE",
    courseCode: "DRV-TRN-HARASSMENT-VIOLENCE",
    categoryId: DRIVER_TRAINING_CATEGORY.WORKPLACE_PROFESSIONAL,
    title: "Harassment / Violence / Respectful Workplace",
    description: "Harassment prevention, workplace violence awareness, and respectful workplace conduct.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-WHISTLEBLOWER",
    courseCode: "DRV-TRN-WHISTLEBLOWER",
    categoryId: DRIVER_TRAINING_CATEGORY.WORKPLACE_PROFESSIONAL,
    title: "Whistleblower / Safety Concern Reporting",
    description: "Reporting safety concerns and protected escalation of workplace or operational issues.",
    version: "1",
    state: "ACTIVE",
  },
  {
    courseId: "DRV-TRN-CUSTOMER-SITE",
    courseCode: "DRV-TRN-CUSTOMER-SITE",
    categoryId: DRIVER_TRAINING_CATEGORY.WORKPLACE_PROFESSIONAL,
    title: "Customer-Site Safety / Professional Conduct",
    description: "Safe conduct at customer sites and professional driver behavior.",
    version: "1",
    state: "ACTIVE",
  },

  // TES-specific corrective training retained as its own course concept.
  {
    courseId: "DRV-TRN-REMEDIAL",
    courseCode: "DRV-TRN-REMEDIAL",
    categoryId: DRIVER_TRAINING_CATEGORY.WORKPLACE_PROFESSIONAL,
    title: "Post-Incident Corrective Re-training",
    description: "Corrective retraining associated with a documented incident or company action.",
    version: "1",
    state: "ACTIVE",
    defaultValidityPeriodMonths: 12,
  },
]
